#include "header.h"
#pragma once

BOOL InjectionProcedure(DWORD pid, CHAR* DLLPath, DWORD OPENPROCESS_TECH, DWORD OPENTHREAD_TECH, DWORD MEMALLOC_TECH, DWORD MEMWRITE_TECH, DWORD INJECT_TECH, DWORD THREADRES_TECH);

